### ISSUE TITLE
Wrong package name in deps in RPM spec

### ISSUE THREAD

**Issue by f-bn** [gbraad/fedora-wsl-genie#2]
Hello,

There is an issue in a dependency name in the RPM spec :

`Requires:      dotnet-runtme-5.0`

should be : 

`Requires:      dotnet-runtime-5.0`

Therefore, the RPM can't be installed : 

```
Retrieving https://github.com/gbraad/fedora-wsl-genie/releases/download/1.34/genie-1.34-1.fc33.x86_64.rpm
error: Failed dependencies:
        dotnet-runtme-5.0 is needed by genie-1.34-1.fc33.x86_64
```

Regards,

**Comment by gbraad** [comment]
Thanks... Fixed in upstream
